(define-module (scmutils))

(eval-when (load compile eval)
           (load-from-path "./src/load.scm"))

;; Add all bindings from generic-environment to the current module
(module-for-each (lambda (sym var)
                   (module-add! (current-module) sym var))
                 generic-environment)

;; Export bindings from generic-environment
(for-each
 (lambda (sym) (module-replace! (current-module) (list sym)))
 '(=
   -
   /
   *
   +
   #{01tensor-field->1form-field}#
   #{10tensor-field->vector-field}#
   #{1form-field->basis-components}#
   #{1form-field->components}#
   #{1form-field-procedure}#
   #{1form-field->tensor-field}#
   #{1form-field->vector-field}#
   #{3vector-components->antisymmetric}#
   #{4-metric}#
   #{4vector->space}#
   #{4vector->time}#
   abs
   abstract-structure-function
   acceleration
   acceleration-tuple
   acos
   acosh
   Alt
   angle
   anticommutator
   antisymmetric->column-matrix
   apply
   arg-scale
   arg-shift
   arity
   asin
   asinh
   atan
   atanh
   background-temperature
   basis?
   basis->1form-basis
   basis->basis-over-map
   basis-components->1form-field
   basis-components->vector-field
   basis->dimension
   basis->vector-basis
   ::c
   canonical?
   canonical-K?
   Cartan?
   Cartan->basis
   Cartan->Christoffel
   Cartan->forms
   C->Cp
   c:generate
   Christoffel
   Christoffel?
   Christoffel->basis
   Christoffel->Cartan
   Christoffel->Cartan-over-map
   Christoffel->symbols
   coefficient-structure->tensor-field
   commutator
   completely-antisymmetric
   components->1form-field
   components->vector-field
   compose
   compositional-canonical?
   conjugate
   contract
   contract-2
   coordinate
   coordinate-basis?
   coordinate-basis-1form-field
   coordinate-basis-1form-field-procedure
   coordinate-basis-vector-field
   coordinate-basis-vector-field-procedure
   coordinate-boost
   coordinate-system->1form-basis
   coordinate-system->basis
   coordinate-system->vector-basis
   coordinate-tuple
   coordinatize
   cos
   cosh
   covariant-derivative
   covariant-differential
   csc
   csch
   cube
   d
   D
   *debugging-simplify-function*
   define-coordinate-system
   define-manifold
   derivative
   determinant
   differential
   differential-of-function
   differential-of-map
   diffop-name
   dot-product
   Dt
   Dt-procedure
   dual-canonical?
   earth-escape-velocity
   earth-gravitational-acceleration
   earth-incident-sunlight
   earth-mass
   earth-mean-density
   earth-orbital-velocity
   earth-radius
   earth-surface-area
   earth-surface-temperature
   Einstein-field-equation
   Einstein-tensor
   *environment*
   Euler-Lagrange-operator
   Euler->M
   Euler->omega
   Euler->omega-body
   Euler-state->L-body
   Euler-state->L-space
   Euler-state->omega-body
   evolution
   excluded-symbols
   exp
   exp10
   exp2
   expt
   exterior-derivative
   exterior-derivative-procedure
   F->C
   F->CT
   ff->tf
   ff:zero
   ff:zero?
   ff:zero-like
   find-invariant-curve
   find-path
   fixed-point-eigen
   F->K
   flow-derivative
   flow-transform
   form-field?
   form-field-over-map
   function->1form-field
   :g
   Gamma
   Gamma-bar
   gcd
   get-rank
   gij
   GMsun
   Gram-Schmidt
   gudermannian
   Hamilton-equations
   Hamiltonian->Lagrangian
   Hamiltonian->Lagrangian-procedure
   Hamiltonian->state-derivative
   has-tensor-manifold?
   H->Hp
   Hodge-star
   Hpendulum
   ->H-state
   Hstate->Lstate
   identity?
   identity-like
   imag-part
   inexact?
   install-coordinates
   instantiate-coordinates
   interior-product
   inverse-gudermannian
   invert
   invert-metric
   J-func
   J*-func
   Lagrange-equations
   Lagrange-equations-1
   Lagrange-equations-first-order
   Lagrange-equations-operator
   Lagrange-explicit
   lagrange-interpolation-function
   Lagrange-interpolation-function
   Lagrangian->acceleration
   Lagrangian-action
   Lagrangian->energy
   Lagrangian->Hamiltonian
   Lagrangian->Hamiltonian-procedure
   Lagrangian->power-loss
   Lagrangian->Routhian
   Lagrangian->state-derivative
   Lagrangian-state->Routhian-state
   L-body
   LE
   Legendre-transform
   Legendre-transform-procedure
   Lie-D
   Lie-derivative
   Lie-transform
   light-year
   linear-function->multiplier
   linear-interpolants
   literal-1form-field
   literal-manifold-function
   literal-manifold-map
   literal-metric
   literal-scalar-field
   literal-vector-field
   ->local
   local-state-derivative
   log
   log10
   log2
   Lorentz-length
   Lorentz-metric
   lower
   ->L-state
   Lstate->Hstate
   :l_sun
   magnitude
   make-4vector
   make-basis
   make-Cartan
   make-Christoffel
   make-constant-vector-field
   make-Hamiltonian
   make-Lagrangian
   make-path
   make-polar
   make-rectangular
   make-SR-coordinates
   make-SR-frame
   make-tensor-field
   manifold-function->tensor-field
   m:antisymmetric?
   memoized-abstract-structure-function
   *memoized-procedures*
   memoized-simplify
   metric->Christoffel-1
   metric->Christoffel-2
   metric->coefs
   metric->connection-1
   metric->connection-2
   metric->inverse-coeffs
   metric:invert
   metric-over-map
   M-of-q->omega-body-of-t
   M-of-q->omega-of-t
   M->omega
   M->omega-body
   momentum
   momentum-tuple
   :m_sun
   multiplicative-transpose
   negate
   Noether-integral
   one?
   one-like
   one-manifold-function
   *optimizing-functions*
   osculating-path
   P
   parametric-path-action
   parsec
   partial
   partial-derivative
   path->state-path
   pendulum-advance
   pendulum-circulating-aa-state-to-state
   pendulum-circulating-action
   pendulum-circulating-action-to-E
   pendulum-circulating-angle
   pendulum-circulating-angular-momentum
   pendulum-circulating-dt
   pendulum-circulating-frequency
   pendulum-circulating-phase
   pendulum-circulating-state-to-aa-state
   pendulum-f
   pendulum-frequency
   pendulum-g
   pendulum-global-aa-state-to-state
   pendulum-Hamiltonian
   pendulum-integration
   pendulum-inverse-f
   pendulum-inverse-g
   pendulum-oscillating-aa-state-to-state
   pendulum-oscillating-action
   pendulum-oscillating-action-to-E
   pendulum-oscillating-angle
   pendulum-oscillating-angular-momentum
   pendulum-oscillating-dt
   pendulum-oscillating-frequency
   pendulum-oscillating-phase
   pendulum-oscillating-state-to-aa-state
   pendulum-separatrix-action
   pendulum-separatrix-angle
   pendulum-separatrix-angular-momentum
   pendulum-state-to-global-aa-state
   pendulum-sysder
   phase-space-derivative
   Phi
   Phi*
   Poisson-bracket
   polar-canonical
   polar-canonical-inverse
   polar/cylindrical
   polar->rectangular
   p->r
   pressure@stp
   principal-range
   procedure->1form-field
   procedure->nform-field
   procedure->vector-field
   pullback
   pullback-form
   pullback-function
   pullback-vector-field
   pushforward-function
   pushforward-vector
   Q
   Qdot
   Qdotdot
   qp->H-state-path
   qp-submatrix
   qv->local-path
   radially-mapping-points
   raise
   rank->arity
   real-part
   real-tuple
   rectangular
   rectangular->polar
   ref
   relative-error
   Ricci-scalar
   Ricci-tensor
   Riemann
   Riemann-curvature
   Riemann-tensor
   room-temperature
   rotate-x-matrix
   rotate-y-matrix
   rotate-z-matrix
   Routh-equations
   Routh-equations-bad
   Routhian->acceleration
   Routhian->acceleration-bad
   Routhian->state-derivative
   Routhian-state->Lagrangian-state
   r->p
   :r_sun
   Rx
   Ry
   Rz
   S2
   sec
   sech
   sharpen
   shift-t
   sigma
   simplify-numerical-expression
   simplify-structure-function
   sin
   sinh
   size
   sound-speed@stp
   speed-of-light
   spherical->rectangular
   sqrt
   square
   s->r
   SR-4vector
   SR-coordinates?
   SR-frame
   SR-name
   s:sigma
   s:sigma/l
   s:sigma/r
   s:sigma/r/l
   ->state
   state->n-dof
   state->p
   state->q
   state->qddot
   state->qdot
   state->qp
   state->t
   structure-constant
   sun-luminosity
   sun-mass
   sun-radius
   sun-rotation-period
   sun-surface-temperature
   symplectic?
   symplectic-matrix?
   symplectic-transform?
   symplectic-two-form
   symplectic-unit
   tan
   tanh
   t:comma
   t:covariant-derivative
   tensor-field?
   tensor-field->coefficient-structure
   tensor-manifold
   tensor-product
   tensor-product2
   tensor-type
   tensor-type?
   T-func
   tf:zero
   tf:zero?
   tf:zero-like
   the-ether
   the-real-line
   time
   time-independent-canonical?
   torsion
   trace
   transpose-function
   T-rigid
   T-rigid-body
   trim-last-argument
   two-particle-center-of-mass
   two-particle-center-of-mass-canonical
   type
   type-predicate
   unstable-manifold
   vector-basis->dual
   vector-field?
   vector-field->1form-field
   vector-field->basis-components
   vector-field->components
   vector-field-over-map
   vector-field-over-map->vector-field
   vector-field-procedure
   vector-field->tensor-field
   velocity
   velocity-tuple
   vf->tf
   vf:zero
   vf:zero?
   vf:zero-like
   vol@stp
   w2
   water-boiling-temperature
   water-freezing-temperature
   wedge
   wedge2
   which-way?
   zero?
   zero-coordinate-function
   zero-like
   zero-manifold-function
   ))

;; Export other scmutils bindings
(export :pi
        :pi/2
        2d-show-expression
        definite-integral
        frame
        literal-function
        multidimensional-minimize
        plot-function
        print-expression pe
        show-expression se
        )

;; Export additional/utility bindings
(export toggle-show-expression-mode)
